import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Twitter,
  User,
  X,
  Home,
  MessageSquare,
  Users,
  Calendar,
  Bookmark,
  Search,
  Bell,
  LogOut,
  UserCheck,
  FileUp,
  Download,
  Upload,
  Phone,
  Video,
  MoreVertical,
  MoreHorizontal,
  Play,
  Pause,
  Mic,
  Paperclip,
  Send,
  Trash,
  Heart,
  MessageCircle,
  Share,
  Lock,
  Globe,
  Flag,
  FileIcon,
  FileSpreadsheet,
  Link,
  Menu,
  Camera,
  TrendingUp,
} from "lucide-react"

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
  warning: AlertTriangle,
  card: CreditCard,
  plus: Plus,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  home: Home,
  message: MessageSquare,
  file: File,
  users: Users,
  calendar: Calendar,
  bookmark: Bookmark,
  search: Search,
  bell: Bell,
  logout: LogOut,
  userCheck: UserCheck,
  fileUp: FileUp,
  download: Download,
  upload: Upload,
  paperclip: Paperclip,
  send: Send,
  phone: Phone,
  video: Video,
  play: Play,
  pause: Pause,
  mic: Mic,
  heart: Heart,
  heartFilled: (props: any) => <Heart {...props} fill="currentColor" />,
  messageCircle: MessageCircle,
  share: Share,
  lock: Lock,
  globe: Globe,
  flag: Flag,
  fileText: FileText,
  filePresentation: FileIcon,
  fileSpreadsheet: FileSpreadsheet,
  link: Link,
  menu: Menu,
  camera: Camera,
  image: Image,
  trendingUp: TrendingUp,
}

